# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d596d091a3bff3426952f178ac98d0d2ee84373ab426a28404c52d60c375762227618862584db006518d13d9990b153f8137d0c4ff51a258339baf5cbdee51a5

test:
  secret_key_base: 46ea02bee20f0b7a122bb581af86db835324a689f0a69afba92d980ffefa97eca333b1c8615aff1c5b6974e8818cc1cfa2c1c5f0cb5c3b0e046e20450c1123df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
